apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml

images:
  - name: ghcr.io/rickcern44/project-thor-api
    newTag: placeholder
  - name: ghcr.io/rickcern44/project-thor-web
    newTag: placeholder
